// Shared content for Resources pages.
// In production, all of this comes from Sanity via a GraphQL/GROQ query.
// Images are placeholder Unsplash URLs — swap for real client/editorial photos at integration.

const RESOURCES = [
  {
    id: 'generic-training-production-ai-strategy',
    type: 'article',
    category: 'AI & Strategy',
    title: 'Generic training was a production problem. AI solved it. Now it\u2019s a strategy problem.',
    dek: 'For twenty years, the honest answer to \u201Cwhy is our training so abstract?\u201D was a production constraint. That constraint is gone. The question has changed.',
    author: 'Yaniv Levi',
    role: 'Founder & CEO',
    readTime: '12 min read',
    publishedAt: '2025-11-14',
    featured: true,
    image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1600&q=80',
  },
  {
    id: 'attention-threshold',
    type: 'article',
    category: 'Learning Science',
    title: 'The attention threshold: why learning fails before it begins.',
    dek: 'Most learning programs lose the learner within the first few minutes. The issue is simpler and more structural than content quality.',
    author: 'Shira Weiss',
    role: 'Head of Learning Design',
    readTime: '10 min read',
    publishedAt: '2025-11-05',
    featured: true,
    image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=1600&q=80',
  },
  {
    id: 'teva-global-compliance',
    type: 'case',
    category: 'Pharma',
    title: 'Teva \u2014 global compliance, localized for 42 countries.',
    dek: 'How we rebuilt Teva\u2019s compliance program into 42 context-aware variants without rewriting content from scratch.',
    client: 'Teva Pharmaceuticals',
    outcomeHeadline: '92% completion rate',
    outcomeSub: 'up from 61% baseline',
    readTime: 'Case study',
    publishedAt: '2025-10-22',
    image: 'https://images.unsplash.com/photo-1576671081837-49000212a370?w=1600&q=80',
  },
  {
    id: 'why-simulation-beats-slide',
    type: 'article',
    category: 'Design',
    title: 'Why a 30-second simulation beats a 30-slide deck.',
    dek: 'The honest math of cognitive load, retrieval practice, and the real cost of linear content in enterprise learning.',
    author: 'Ariel Ben-David',
    role: 'Principal Designer',
    readTime: '7 min read',
    publishedAt: '2025-10-14',
    image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=1600&q=80',
  },
  {
    id: 'insight-role-play',
    type: 'insight',
    category: 'Insight',
    title: 'Role-play at scale is the unlock. Not video. Not quizzes.',
    dek: 'After 200+ enterprise programs, the single highest-leverage format is the one leaders keep cutting first.',
    author: 'Yaniv Levi',
    role: 'Founder & CEO',
    readTime: '3 min read',
    publishedAt: '2025-10-08',
    image: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=1600&q=80',
  },
  {
    id: 'monday-onboarding-reboot',
    type: 'case',
    category: 'SaaS',
    title: 'Monday.com \u2014 the onboarding that unlocked 1,200 new engineers.',
    dek: 'A 14-day ramp replacing a 90-day wander. Built around simulation, not documentation.',
    client: 'Monday.com',
    outcomeHeadline: '14 days to productive',
    outcomeSub: 'vs. 90-day baseline',
    readTime: 'Case study',
    publishedAt: '2025-09-30',
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1600&q=80',
  },
  {
    id: 'measuring-capability',
    type: 'article',
    category: 'Measurement',
    title: 'You can\u2019t measure capability with a quiz. Here\u2019s what works.',
    dek: 'Capability is context-dependent. Your measurement instruments should be too. A field guide.',
    author: 'Dr. Noa Katz',
    role: 'Learning Analytics Lead',
    readTime: '9 min read',
    publishedAt: '2025-09-22',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600&q=80',
  },
  {
    id: 'insight-microlearning-myth',
    type: 'insight',
    category: 'Insight',
    title: '\u201CMicrolearning\u201D is a length. It\u2019s not a strategy.',
    dek: 'Short content without a learning architecture is just short, forgettable content.',
    author: 'Shira Weiss',
    role: 'Head of Learning Design',
    readTime: '2 min read',
    publishedAt: '2025-09-15',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1600&q=80',
  },
  {
    id: 'checkpoint-security-awareness',
    type: 'case',
    category: 'Cybersecurity',
    title: 'Check Point \u2014 security awareness that people actually finish.',
    dek: 'A narrative-driven program that treated employees as defenders, not liabilities.',
    client: 'Check Point Software',
    outcomeHeadline: '3.4\u00D7 phishing resilience',
    outcomeSub: 'measured 6 months post-launch',
    readTime: 'Case study',
    publishedAt: '2025-09-02',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1600&q=80',
  },
  {
    id: 'insight-leadership-coaching',
    type: 'insight',
    category: 'Insight',
    title: 'Leadership programs are coaching engines in disguise.',
    dek: 'The content matters. The conversation around it matters more. Design for both.',
    author: 'Yaniv Levi',
    role: 'Founder & CEO',
    readTime: '3 min read',
    publishedAt: '2025-08-24',
    image: 'https://images.unsplash.com/photo-1552581234-26160f608093?w=1600&q=80',
  },
  {
    id: 'ai-personas-in-learning',
    type: 'article',
    category: 'AI & Strategy',
    title: 'AI personas: the practice room we never had.',
    dek: 'A new primitive in learning design. What it is, where it wins, and where it still breaks.',
    author: 'Ariel Ben-David',
    role: 'Principal Designer',
    readTime: '11 min read',
    publishedAt: '2025-08-12',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1600&q=80',
  },
  {
    id: 'amdocs-ai-enablement',
    type: 'case',
    category: 'Telecom',
    title: 'Amdocs \u2014 AI enablement for 30,000 engineers.',
    dek: 'Turning a tool rollout into a capability program. Role-by-role, team-by-team.',
    client: 'Amdocs',
    outcomeHeadline: '78% adoption at 90 days',
    outcomeSub: 'vs. 22% industry benchmark',
    readTime: 'Case study',
    publishedAt: '2025-07-28',
    image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1600&q=80',
  },
];

const CATEGORIES = ['All', 'AI & Strategy', 'Learning Science', 'Design', 'Measurement', 'Pharma', 'SaaS', 'Cybersecurity', 'Telecom'];
const TYPES = [
  { key: 'all', label: 'All', plural: 'All' },
  { key: 'article', label: 'Article', plural: 'Articles' },
  { key: 'case', label: 'Case', plural: 'Case studies' },
  { key: 'insight', label: 'Insight', plural: 'Short insights' },
];

function formatDate(iso) {
  const d = new Date(iso);
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

Object.assign(window, { RESOURCES, CATEGORIES, TYPES, formatDate });
